export interface Brand {
  id: string;
  name: string;
  description: string;
  websiteUrl: string;
  country: string;
}

// Type for creating a new brand (without id, which is generated by the backend)
export type CreateBrandDto = Omit<Brand, "id">;
